/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Shalva
 */
public class Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGDistribuidor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RdbCofarma = new javax.swing.JRadioButton();
        RdbEmpsephar = new javax.swing.JRadioButton();
        RdbCemefar = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cbxPrincipal = new javax.swing.JCheckBox();
        cbxSecundario = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Pedido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("•Nombre del Medicamento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtNombreM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(txtNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("•Tipo del Medicamento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        jPanel1.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("•Cantidad del Producto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtCantidadP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(txtCantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 200, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("•Distribuidor Farmacéutico ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        btnGDistribuidor.add(RdbCofarma);
        RdbCofarma.setText("COFARMA");
        jPanel1.add(RdbCofarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        btnGDistribuidor.add(RdbEmpsephar);
        RdbEmpsephar.setText("EMPSEPHAR");
        jPanel1.add(RdbEmpsephar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        btnGDistribuidor.add(RdbCemefar);
        RdbCemefar.setText("CEMEFAR");
        jPanel1.add(RdbCemefar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("•Sucursal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        cbxPrincipal.setText("PRINCIPAL ");
        jPanel1.add(cbxPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        cbxSecundario.setText("SECUNDARIA");
        jPanel1.add(cbxSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        btnOK.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnOK.setText("OK");
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/0cdb31fe5dbaceca18479548d145516b.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JRadioButton getRdbCemefar() {
        return RdbCemefar;
    }

    public void setRdbCemefar(JRadioButton RdbCemefar) {
        this.RdbCemefar = RdbCemefar;
    }

    public JRadioButton getRdbCofarma() {
        return RdbCofarma;
    }

    public void setRdbCofarma(JRadioButton RdbCofarma) {
        this.RdbCofarma = RdbCofarma;
    }

    public JRadioButton getRdbEmpsephar() {
        return RdbEmpsephar;
    }

    public void setRdbEmpsephar(JRadioButton RdbEmpsephar) {
        this.RdbEmpsephar = RdbEmpsephar;
    }

    public ButtonGroup getBtnGDistribuidor() {
        return btnGDistribuidor;
    }

    public void setBtnGDistribuidor(ButtonGroup btnGDistribuidor) {
        this.btnGDistribuidor = btnGDistribuidor;
    }

    public JButton getBtnOK() {
        return btnOK;
    }

    public void setBtnOK(JButton btnOK) {
        this.btnOK = btnOK;
    }

    public JCheckBox getCbxPrincipal() {
        return cbxPrincipal;
    }

    public void setCbxPrincipal(JCheckBox cbxPrincipal) {
        this.cbxPrincipal = cbxPrincipal;
    }

    public JCheckBox getCbxSecundario() {
        return cbxSecundario;
    }

    public void setCbxSecundario(JCheckBox cbxSecundario) {
        this.cbxSecundario = cbxSecundario;
    }

    public JComboBox<String> getCbxTipo() {
        return cbxTipo;
    }

    public void setCbxTipo(JComboBox<String> cbxTipo) {
        this.cbxTipo = cbxTipo;
    }

    public JTextField getTxtCantidadP() {
        return txtCantidadP;
    }

    public void setTxtCantidadP(JTextField txtCantidadP) {
        this.txtCantidadP = txtCantidadP;
    }

    public JTextField getTxtNombreM() {
        return txtNombreM;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtNombreM(JTextField txtNombreM) {
        this.txtNombreM = txtNombreM;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdbCemefar;
    private javax.swing.JRadioButton RdbCofarma;
    private javax.swing.JRadioButton RdbEmpsephar;
    private javax.swing.ButtonGroup btnGDistribuidor;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbxPrincipal;
    private javax.swing.JCheckBox cbxSecundario;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidadP;
    private javax.swing.JTextField txtNombreM;
    // End of variables declaration//GEN-END:variables
}
